### ISSUE TITLE
fstab: support ID=<id> like UUID=<uuid>

### ISSUE THREAD

**Issue by ilf** [karelzak/util-linux#1008]
[fstab.5 sais](https://github.com/karelzak/util-linux/blob/master/sys-utils/fstab.5#L86):

> `LABEL=<label>` or `UUID=<uuid>` may be given instead of a device name. This is the recommended method, as device names are often a coincidence of hardware detection order, and can change when other disks are added or removed.

Besides `LABEL=<label>` and `UUID=<uuid>`, `/dev/disk/` also has `ID=<id>`. But that's currently not supported by fstab. Is there a reason for this? I can't see one.

It would be awesome to support `ID=<id>` in fstab, too. Should be trivial. Thanks!

**Comment by karelzak** [comment]
The command mount(8) is able to convert LABEL=, UUID=, PARTLABEL=, PARTUUID= into device name without udev or any other dependence. 

Unfortunately, ID= is different, it's generated by udev only. It would be possible to support it (use the symlink in /dev), but I'm not sure it's really necessary. Do you have any use-case where ID= is better than the other tags?

Anyway, you can use directly /dev/disk/by-id/<name> symlink (rather than ID=<name>) in your fstab. The symlink is created by udev when disk added to the system.

**Comment by ilf** [comment]
`UUID` and `LABEL` can be changed with software, `ID` never changes, it's [assigned by the hardware manufacturer](https://documentation.suse.com/sles/11-SP4/html/SLES-all/uuid.html#usinguuid). That can make it preferrable to use `ID`, f.e. across file system changes and formats.

Yes, we can use `/dev/disk/by-id/` (that's what I'm doing), but we can also use `/dev/disk/by-uuid/`, still we make it more accessible (and prettier) by allowing `UUID=`, but not `ID=`. IMHO that's inconsistent.

**Comment by karelzak** [comment]
It seems ID= in  /dev/disk/by-id/ is used by udev in a very creative way and not strictly defined. It generates many identifiers for the same device etc.

Would it be better to be more strict and introduce WWN=<string>, which will be internally translated to /dev/disk/by-id/wwn-<string>?

I think for users with some advanced storage setups it will be more native way to address block device device than generic ID=.

**Comment by ilf** [comment]
I'm sure `WWN=` might be useful for some.

But I like `ID=` because it's unique *and* human-meaningful. I can monitor devices with those names and immediately identify them physically, because the device ID is printed on them.

**Comment by karelzak** [comment]
Implemented.

**Comment by ilf** [comment]
Thank you, @karelzak!
