### ISSUE TITLE
hwclock/systohc seems to be flaky on Travis CI

### ISSUE THREAD

**Issue by evverx** [karelzak/util-linux#1082]
To judge from https://travis-ci.org/github/karelzak/util-linux/jobs/703166322, it seems the test fails from time to time with
```
      hwclock: system to hw                   ... FAILED (offsets 216.218.254.202: +0.018064 -0.998979 +/-1.017043)
```

**Comment by karelzak** [comment]
Hmm... frankly use hwlock in this environment is probably fragile. I guess it's some container or virtual machine and in this case do anything with HW clock or assume small latencies is a bad idea. 

Maybe we can detect that at the beginning of the test that it's virtual machine or container and call ts_skip rather than execute the test (or introduce ts_skip_nonhw function).

**Comment by evverx** [comment]
I run that test in VMs and containers and it seems to be fine there so I'd probably skip it on Travis CI only for the time being.

Looking at https://travis-ci.org/github/karelzak/util-linux/jobs/704172347 where it's just failed, it seems it happens on Travis CI when `dist` is precise so probably I could add call `ts_skip` when those conditions are met. I need to figure out what environment variables I should check though.

**Comment by evverx** [comment]
It should be addressed in https://github.com/karelzak/util-linux/pull/1090
