### ISSUE TITLE
lsblk replaces space with underscore

### ISSUE THREAD

**Issue by ltrager** [karelzak/util-linux#1098]
I have two scripts which run on hardware. The first one gathers storage information by scanning /sys. The second one executes commands against storage hardware by using lsblk to look up the block device path by matching the storage device model and serial. lsblk is replacing spaces with underscores which breaks the mapping. lsblk should NOT be changing device information.

You can reproduce this with QEMU by emulating an IDE disk

Information from # cat /sys/block/sda/device/wwid 
t10.ATA     QEMU HARDDISK                           QM00001

Information from lsblk --exclude 1,2,7 -d -P -o NAME,MODEL,SERIAL
NAME="sda" MODEL="QEMU_HARDDISK" SERIAL="QM00001"

**Comment by karelzak** [comment]
We read this information from udev db rather than from /sys
* MODEL in /sys is truncated to 16 chars, but udev provides full size, see https://github.com/karelzak/util-linux/issues/690
* SERIAL is pretty often not available in /sys, see https://github.com/karelzak/util-linux/issues/33

lsblk does not modify this data and I'm not sure if there is a way how to improve this situation;-(

**Comment by t-8ch** [comment]
udev should also provide a property `ID_MODEL_ENC` that can be decoded into the value including spaces.
For example:
```
E: ID_MODEL=xHCI_Host_Controller
E: ID_MODEL_ENC=xHCI\x20Host\x20Controller
```

**Comment by karelzak** [comment]
> udev should also provide a property `ID_MODEL_ENC` that can be decoded into the value including spaces.
> For example:
> 
> ```
> E: ID_MODEL=xHCI_Host_Controller
> E: ID_MODEL_ENC=xHCI\x20Host\x20Controller
> ```

That's a good point! Implemented.
