### ISSUE TITLE
2.36.1 breaks user mounts on kernels < 5.10

### ISSUE THREAD

**Issue by heftig** [karelzak/util-linux#1193]
Since 2.36.1, trying to mount a user mount defined in fstab fails because the `symfollow` option is unknown.

https://www.linuxquestions.org/questions/slackware-14/util-linux-2-36-1-breaks-fuse-sshfs-4175685400/
https://bugs.archlinux.org/task/68660

As far as I can tell, the lines that insert the option

https://github.com/karelzak/util-linux/blob/95c706c9c2ae2d7e1f095713dae68c7f9cc2462d/libmount/src/context_mount.c#L425-L426

are wrong anyway, because `MS_NOSYMFOLLOW` is not part of `MS_SECURE`, so `nosymfollow` is not implied by user mounts and `symfollow` does not need to be added.

**Comment by karelzak** [comment]
Unfortunately, you're right ;-) Fixed, the change will be available in v2.36.2.

Note to the linuxquestions.org discussion, fuse user mounts are supported since v2.35 without user= in your fstab (or without fstab enatry at all). man mount:
```
Since  version  2.35  mount  command does not exit when user permissions are inadequate by internal libmount security
rules.  It drops suid permissions and continue as regular non-root user. It allows to support  use-cases  where  root
permissions are not necessary (e.g., fuse filesystems, user namespaces, etc).
```
It means you can as regular user use
```
mount -t fuse.sshfs kzak@192.168.111.1:/home/kzak /home/kzak/mnt
```
as well as 
```
umount /home/kzak/mnt
```
on your command line without any entry in your fstab.

**Comment by dima4p** [comment]
Wenn do you plan to issue 2.36.2?

**Comment by karelzak** [comment]
> Wenn do you plan to issue 2.36.2?

This week I hope.
