### ISSUE TITLE
Feature Request: ipcs - apply --human processing to --summary option

### ISSUE THREAD

**Issue by MrPippin66** [karelzak/util-linux#1199]
In current version of "ipcs", '--human' does not additional processing with the '--summary' flag.

I.E. adding the --human flag does nothing.

#  ipcs -mu

------ Shared Memory Status --------
segments allocated 15
pages allocated 12845335
pages resident  10884516
pages swapped   340733
Swap performance: 0 attempts     0 successes

# ipcs -mu --human

------ Shared Memory Status --------
segments allocated 15
pages allocated 12845335
pages resident  10884516
pages swapped   340733
Swap performance: 0 attempts     0 successes

It would be useful to have --human provide units in B,M,G,T like is done without the --summary flag added.

**Comment by kerolasa** [comment]
Would it be acceptable to consider `lsipc -m` as an utility to print ipc information? It prints by default human readable sizes, that can be changed to `--bytes` with an appropriately named option.

**Comment by MrPippin66** [comment]
The issue is specific to the '--summary' option, which reports the values in blocks. The '--bytes' option doesn't change the reporting for the '--summary' option, either.

**Comment by kerolasa** [comment]
I think you mean `pages allocated`. I have feeling `--human` does not take effect because these are counted in pages, and megapage is not a thing. Taking the number, multiplying by page size, and converting to `--human` units is doable, but that invalidates textual output. Unless it is made to change when unit change is requested. Maybe something similar should be added to `lsipc` as well.

Do I guess right that this request boils down to observation the currently reported number in your example output is hard to read as how much is it?

**Comment by MrPippin66** [comment]
Yes, I would prefer an option that reports it in easily understandable values.

**Comment by karelzak** [comment]
I understand your point of view, the question is if add new features to ipcs is the way we want to go. We already have lsipc to provide a nice and human friendly output. The command ipcs is there mostly for backward and POSIX compatibility.

My suggestion is to (move forward in command line development and) use lsipc :-)
