### ISSUE TITLE
Inconsistent number formatting for `MHZ` column.

### ISSUE THREAD

**Issue by t-8ch** [karelzak/util-linux#1316]
It seems the formatting of the `MHZ` column is not subject to the current locale.
Tested on aa049eabb32934f03ee102a569443ac725d4ae61.

Example:
```sh
$ LC_ALL=de_DE.UTF-8 ./lscpu -e=CPU,MHZ,MAXMHZ
CPU      MHZ    MAXMHZ
  0  700.005 2800,0000
  1 2400.000 2800,0000
  2  732.465 2800,0000
  3 2400.000 2800,0000
```

**Comment by t-8ch** [comment]
Sidenote: Is it intentional that all the values in the JSON output are strings instead of numbers for actual numbers?

**Comment by karelzak** [comment]
Ah, it seems we both work in the same area ;-) I'll integrate this your change to the "next" branch. Thanks.

**Comment by t-8ch** [comment]
Also, as libsmartcols emits the cell value verbatim in case of `SCOLS_JSON_NUMBER` this will only work when the active locale has a JSON-compatible number format.
In other cases either the JSON is unparseable.
Users of libsmartcols would have know this and make sure to always generate JSON-compatible numbers.
But this will also mean that the numbers for the non-JSON will now not be in the users locale anymore.

**Comment by karelzak** [comment]
Ad MHZ number: I have used cpu->mhz_cur_freq which has been introduced in the previous patch. So, now it's locale-sensitive. Fixed in "next" branch.

Ad JSON: we need to call scols_column_set_json_type(), see how it's implemented in misc-utils/lsblk.c. Please, report it as a separate issue. It's easy to fix. 

Anyway, libsmartcols do not maintain the content of the cells in original data formats (for good reason), it's internally all about strings. It's the caller's responsibility to prepare what is need for the output. Yes, JSON vs. locale is a problem, maybe all we need is to not call setlocale() when --json is requested.

**Comment by t-8ch** [comment]
I'll send a PR against next for the JSON types.

FYI `next` does currently not build.

**Comment by karelzak** [comment]
I have rebased "next" to be up to date with "master". (I don't like rebase and force-push in public branches, but in this case it's for active developers, etc ... :-) )

**Comment by t-8ch** [comment]
The problem was that I had old generated files from autoconf in my source tree that then got picked up before the meson-generated header files in the build directory. No idea why it wasn't an issue on master.
