### ISSUE TITLE
Release tarball and man page

### ISSUE THREAD

**Issue by xry111** [karelzak/util-linux#1327]
The tarball at https://kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.tar.xz does not contain man pages anymore.  Is this intentional?

Another issue: meson.build is now in the git repository, but it's not shipped in the tarball.  

And, there is some glitch in the man page generated by asciidoctor-2.0.15 (util-linux-2.37 was configured using configure script in the tarball instead of meson, as meson.build is not in the release tarball).  In the end it says `util-linux {release-version}`, instead of `util-linux 2.37`.

**Comment by karelzak** [comment]
Yes, it's intentional. The content of the man pages depends on configuration in some cases.

meson.build -- for now it's designed for developers only. It's incomplete and experimental, it does not make sense to distribute it with the tarball. I guess in the next releases it will be more usable and we will distribute it (I hope:-)

The {release-version} is a bug ... it will be fixed in v2.37.1. Thanks for your report!

**Comment by karelzak** [comment]
Note that in the previous releases we had incomplete man pages in the tarball too, and during the build process, it was converted to the final man page (e.g. hwclock.8.in -->  hwclock.8).
