### ISSUE TITLE
The usage of the word "bad" should be avoided

### ISSUE THREAD

**Issue by bodqhrohro** [karelzak/util-linux#1345]
[According to Wiktionary](https://en.wiktionary.org/wiki/bad#English), the word "bad" *presumably* descends to Old English "bæddel", which means "hermaphrodite", and thus implies a disrespect to non-binary persons.

The word "bad" occurs quite a lot in the source code of `util-linux`, and should be replaced whenever possible. For example, the established term "bad sector", which is used in `fsck` and `mkfs`, can be replaced with "corrupted sector", which is even more concrete and informative. And the term "bad usage", which is used in numerous utilities — not just in the code, but in messages printed to a user — can be replaced with "improper usage" or "unintended usage".

**Comment by karelzak** [comment]
Well, I understand why words like `blacklist` or `master` sound inadequate in some contexts, but try to replace the word `bad` due to some **presumably meaning in Old English** sounds like pretty strange overkill. I have full respect for non-binary people, but I guess nobody in these days sees any relation between "bad" and  "hermaphrodite", and I do not think that here on the util-linux issue tracker is the right place to start a discussion about our dictionary improvements.

**Comment by tbzatek** [comment]
FYI, an important aspect to keep in mind is that any existing string printed out may be used by other tools in case where library API is not available and consumers are forced to parse standard output (and error output). Just like commandline switches the printed output should be treated as ABI and have some degree of stability guarantee. Any such change may cause breakage on other sides.

**Comment by mator** [comment]
can we please close this issue early, thanks.

**Comment by bodqhrohro** [comment]
>NEEDINFO

What info?
