### ISSUE TITLE
Tar archives on github missing `.tarball-version` file.

### ISSUE THREAD

**Issue by igo95862** [karelzak/util-linux#1381]
Github releases page:

https://github.com/karelzak/util-linux/releases

The archivies from https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/ do include this file.

Lack of this file causes all libraries report UNKNOWN version.

**Comment by karelzak** [comment]
The best way would be to disable the tarballs from GitHub at all (https://github.community/t/disable-tarball/139966/3). The official project tarballs are generated by the maintainer, signed, and distributed by kernel.org, everything else is non-sense.

... but I have added a workaround to tools/git-version-gen to read the version from NEWS rather than use UKNOWN.
