### ISSUE TITLE
libmount: mnt_pretty_path memleak

### ISSUE THREAD

**Issue by FedeDP** [karelzak/util-linux#275]
Hi!

I found out that mnt_pretty_path will memleak in case of loop device, as it calls loopcxt_init, but then suddenly returns tmp, if a backing file was found, without calling loopcxt_deinit.
This patch fixes that.
Plus, it removes the check for "loopcxt_is_autoclear": is there any reason that check is there? I don't understand it.

Thanks for your time and for your efforts.

[cache_patch.txt](https://github.com/karelzak/util-linux/files/123022/cache_patch.txt)

EDIT: do you prefer a PR?

**Comment by karelzak** [comment]
Good catch! PR are fine, but no required :-)

There are two ways how you can create and mount loop device:

1) mount -o loop file.img
- you have specified image file and you probably expect file.img path in the mount(8) output. In this case loop is marked by "autoclear" flag.

2) losetup -f file.img; mount /dev/loopN
- you have created device and mounted device, so you probably expect /dev/loopN in the mount(8) output.

From pedantic point of view only 2 is the right thing, because mounted is always device although on mount(8) command line you have specified something else, BUT for backward compatibility people assume 1) if  an image file has been specified.

Your patch changes this semantic and for all loop devices it prints backing file. It would be nice keep loopcxt_is_autoclear() there :-)

**Comment by FedeDP** [comment]
As i use second method, i did not think about that :)
I'm wondering how can i check a loopdev backing file then (without counting for its autoclear flag): it seems i cannot call loopdev.h functions just including libmount in my code.

new patch: [cache_patch.txt](https://github.com/karelzak/util-linux/files/124998/cache_patch.txt)

**Comment by karelzak** [comment]
> I mean, checking autoclear seems not very trustworthy to me.
That's right, it's fragile. It's only about common use-case and backward compatibility. IMHO it's good enough for this purpose.

Personally I don't like mount(8) output, because it's non-extendible, it provides very simplified point of view, etc, but it's used on many many places by scripts etc.

The recommended way is to use findmnt(8) to see mount table and losetup for loopdevs.

**Comment by karelzak** [comment]
Fixed, thanks!

**Comment by FedeDP** [comment]
Again. thanks for your time :)
