### ISSUE TITLE
blkid -o export -s UUID should not show DEVNAME

### ISSUE THREAD

**Issue by ignatenkobrain** [karelzak/util-linux#401]
```
# blkid /dev/mapper/luks-b9f6b9aa-e660-42a7-89a7-a5e9583cb9c8  -o export -s UUID
DEVNAME=/dev/mapper/luks-b9f6b9aa-e660-42a7-89a7-a5e9583cb9c8
UUID=51cefdb3-3c5a-4cb6-8eda-c4e69c1dd437
```

I think point of `-s` is to hide all of other attributes, not just some of them

**Comment by ignatenkobrain** [comment]
Actually, I workarounded this by `-o value`, but still not sure if export should really show devname.

**Comment by karelzak** [comment]
Well, see
```
# blkid /dev/sda3  -s UUID
/dev/sda3: UUID="196972ad-3b13-4bba-ac54-4cb3f7b409a4"
```
it always prints devname, because you can ask for info about more devices, this is reason why we also use it in the export output format.
```
# blkid /dev/sda3 /dev/sda4 -o export -s UUID
DEVNAME=/dev/sda3
UUID=196972ad-3b13-4bba-ac54-4cb3f7b409a4

DEVNAME=/dev/sda4
UUID=d834bc84-0089-4be1-9013-cd8bf35d5ffa
``` 
Anyway, it's recommended to use lsblk that works also for non-root users and provides better control on output format.
```
$ lsblk /dev/sda3 --pairs -o UUID
UUID="196972ad-3b13-4bba-ac54-4cb3f7b409a4"
```
This is what you're looking for, I guess :-)
