### ISSUE TITLE
sfdisk: totally different behavior when specifying partition size in sectors vs megabytes

### ISSUE THREAD

**Issue by r-tty** [karelzak/util-linux#417]
**OS: Debian 9
Steps to reproduce:**

$ sfdisk --version
sfdisk from util-linux 2.29.1
$ dd if=/dev/zero of=file bs=1024 count=10240
$ echo 'start=512, size=4096, type=0x83, bootable
size=512K,  type=7
size=1M,    type=0x4e' | sfdisk file

Disk file: 10 MiB, 10485760 bytes, 20480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Created a new DOS disklabel with disk identifier 0x07c31d2f.
file1: Created a new partition 1 of type 'Linux' and of size 2 MiB.
file2: Created a new partition 2 of type 'HPFS/NTFS/exFAT' and of size 512 KiB.
file3: Created a new partition 3 of type 'QNX4.x 2nd part' and of size 1 MiB.
file4: Done.

New situation:

Device Boot Start   End Sectors  Size Id Type
file1  *      512  4607    4096    2M 83 Linux
file2        6144  7167    1024  512K  7 HPFS/NTFS/exFAT
file3        8192 10239    2048    1M 4e QNX4.x 2nd part

**The command above worked correctly. The same request, but with first partition size given in megabytes (2MB):**

$ dd if=/dev/zero of=file bs=1024 count=10240
$ echo 'start=512, size=2M, type=0x83, bootable
size=512K,  type=7
size=1M,    type=0x4e' | sfdisk file

Disk file: 10 MiB, 10485760 bytes, 20480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

>>> Created a new DOS disklabel with disk identifier 0x2e2ccf5f.
file1: Created a new partition 1 of type 'Linux' and of size 1.8 MiB.
file2: Created a new partition 2 of type 'HPFS/NTFS/exFAT' and of size 512 KiB.
file3: Created a new partition 3 of type 'QNX4.x 2nd part' and of size 1 MiB.
file4: Done.

New situation:

Device Boot Start   End Sectors  Size Id Type
file1  *      512  4095    3584  1.8M 83 Linux
file2        4096  5119    1024  512K  7 HPFS/NTFS/exFAT
file3        6144  8191    2048    1M 4e QNX4.x 2nd part

**3584 sectors were allocated, instead of requested 4096.
Specifying parameters as '512,2M,0x83,*' has the same effect.
Giving "MiB" or "MB" or "mb" does not change anything (!), same 3584 sectors are allocated.**

**Comment by karelzak** [comment]
man sfdisk:

"...however if the size is followed by one of the multiplicative suffixes (KiB, MiB, GiB, TiB, PiB, EiB, ZiB and YiB) then the number is interpreted as  the  size  of  the  partition  in  bytes  and  it is then aligned according to the device I/O limits."
--

The default is to align to the megabytes boundary to make partition tables portable as much as possible (4K disks, I/0 limits, etc.), the partition starts at 512 and size is 3584, the "next right" alignment in this case is offset 4096 (=512+3584). 

This is expected behaviour.

Yes, it may look strange for very small sizes and in this case it's better to use exact numbers in sectors (but then don't complain for unaligned partitions).

I'll add some note to the man page to better explain this behaviour.

**Comment by karelzak** [comment]
BTW, see in your first example the gap between the first and second partition:
```
file1 *    512 4607 4096   2M 83 Linux
file2     6144 7167 1024 512K  7 HPFS/NTFS/exFAT
```
the start sector for the second partition has not been specified, so the default is to the next aligned offset.

The recommend way is to not specify start offset at all, and use sizes only:
```
# echo 'size=2M, type=0x83, bootable
size=512K, type=7
size=1M, type=0x4e' | sfdisk /dev/sdc
...
Device     Boot Start   End Sectors  Size Id Type
/dev/sdc1  *     2048  6143    4096    2M 83 Linux
/dev/sdc2        6144  7167    1024  512K  7 HPFS/NTFS/exFAT
/dev/sdc3        8192 10239    2048    1M 4e QNX4.x 2nd part
```
