### ISSUE TITLE
About --wipe-partitions

### ISSUE THREAD

**Issue by tomty89** [karelzak/util-linux#437]
Hello Karel.

So I notice a prompt about filesystem signature wiping when create partitions with fdisk, then I found out about --wipe-partition introduced im commit ba46562.

First of all, I have no idea why this is even introduced since anyone want the signature wiped/replaced can run wipefs/mkfs subsequently. IMHO it's a really bad idea for a partitioning utility be involved in filesystem manipulation, and I think it's quite a general opinion as well. (For case like GParted, to me it's merely because it's trying to provide "Windows experience" so that it doesn't mind deepening the partition/filesystem confusion).

I have to admit I didn't tested it thoroughly, so I am not sure about it's actual behavior, but I will just list my concerns/suggestions anyway:

1. does it wipe the filesystem signatures before the partition table is saved? since fdisk does not write to disk before 'w' (which is super good) when it manipulate partition table entry, I don't suppose it logically make sense if it wipe the fs signature before 'w'.

2. If it does wipe on 'w', do you think it's better that "p" would show a column showing that whether each of the partitions would get wiped? maybe even a menu item to toggle the "wipe flag"? (which might be better than prompts)

3. what happen if I just press enter to the prompt without saying yes or no? does it at least ask until I give a proper answer or default to no?

4. do you think it's better to default the switch to never (if not getting rid of the feature totally), so at least only people who "feel like" they really need the prompt/feature would need to start fdisk with a switch explicitly specified?

**Comment by karelzak** [comment]
Well, if you leave fdisk then all new partitions (and content on the partitions) are automatically visible for the system. It means udev scans the content, another infrastructure maybe triggered etc. In some cases this is unwanted and it seems more elegant to produce by fdisk partitions that are without some side-effects. We don't do any filesystem manipulations, it just write zeros to the device to be sure that it's "empty" from system point of view.

1. nothing on the disk is modified before 'w'

2. good idea, add something like "WILL WIPE" to 'p' sounds good.

3. nothing, successful rpmatch() is required

4. the default is "auto", it means that user confirmation in interactive mode is required if a valid FS superblok is detected, otherwise nothing is wiped. IMHO it's safe enough.

Note that goal is to produce wiped devices by all mkfs-like and partitioning tools (if possible). We have pretty bad experience with non-wiped disks and collisions. 

I believe that (s)fdisk is still driven by user and it does not try to be more smart than user. It warns you and offer a solution, that's all.

**Comment by marcosfrm** [comment]
> do you think it's better to default the switch to never (**if not getting rid of the feature totally**), so at least only people who "feel like" they really need the prompt/feature would need to start fdisk with a switch explicitly specified?

Please no. The feature is very useful, as it allows us to have a signature-clean partition without needing to play games with udev (udevadm et al.). I am fine if the default changes though.

**Comment by tomty89** [comment]
@marcosfrm udev? What does it have to do with this at all? You can have a signature-clean partition by running `wipefs`.

**Comment by marcosfrm** [comment]
Any change in the partition table will trigger udev scanning once the device is closed. While udev keeps the device open, we cannot run anything on it: wipefs, mkfs, whatever. In automated scenarios, we can avoid this guarding *fdisk commands with `udevadm settle`. But why bother if `sfdisk --wipe-partitions=always` (and if partition table itself is going to be rebuilt `--wipe=always`) does the job at once? BTW, SUSE folks did the same in Parted:

https://build.opensuse.org/package/view_file/openSUSE:Factory/parted/parted-implement-wipesignatures-option.patch?expand=1

I only care about `sfdisk` in my automated setups.

**Comment by tomty89** [comment]
@marcosfrm I am still not sure what was your experience:

> trigger udev scanning once the device is closed. While udev keeps the device open

Why would udev _keep_ it open? Do you mean udev can be stalled by some filesystem signature change in some case?

> In automated scenarios, we can avoid this guarding *fdisk commands with udevadm settle.

Hmm, or I guess you mean your automated script starts mkfs/wipefs "real soon" so they can be skipped sometime.

As you've suggested, in automated scenario, script writers would be using sfdisk. Not to mention that it is much more appropriate requiring them to set the wipe option explicitly (because automated scenarios should really be considered as special cases; while udevadm settle is available, it is more than enough to additionally provide an option to do it with sfdisk; providing that in the interactive fdisk is simply too much, let alone making the bugging prompts the default).

If it is udev that needs to be guarded, then it should done in the udev way, instead of tainting partitioning tools by making them able to mess with areas outside of where filesystem table resides.

**Comment by marcosfrm** [comment]
> Why would udev keep it open? Do you mean udev can be stalled by some filesystem signature change in some case?

Keep for a very short timeframe. Still a huge problem on automated setups. Yep, udev will scan if there are signatures inside each partition AFAIK.

There was a bug I reported on openSUSE Bugzilla (with multiple duplicates) because this. YaST (SUSE's installer) would run `wipefs -a DEV` (from C++ code, before mkfs) and it would just fail because udev was doing its stuff keeping the device open. They implemented that patch I linked in Parted to fix it.

> EDIT: but then these would not happen if there is no existing filesystem signature on the new partition(s)? 

Maybe not (need to check in udev's code). But when there *are* signatures, we are doomed.

> If it is udev that needs to be guarded, then it should done in the udev way, but not by tainting partitioning tools by making them able to mess with areas outside of where filesystem table resides.

This mechanism exists since systemd/udev 213:

https://github.com/systemd/systemd/commit/3ebdb81ef088afd3b4c72b516beb5610f8c93a0d

But I am unaware of any partitioning tool adopting it.

I understand your concern. Perhaps util-linux's default should be changed. I really do not care, provided that an option to enable the wiping is kept.

**Comment by karelzak** [comment]
What is the problem with the current default? It will ask in interactive session, otherwise (non-interactive mode) it will require command line option. It's safe and better that assume that users care about this stuff and always call wipefs.

And note that we already wipe from whole-disk device and it's necessary, so "care about PT only" is not true...

**Comment by tomty89** [comment]
@marcosfrm 
> Maybe not (need to check in udev's code).
That's the point. If it is a udev's flaw/bug, then it should be fix. If it is the partitioning tool / automated script / distro installer not _working with udev_ in an appropriate way, then they should be fixed. Adding (and defaulting) the partitioning tool to do something _it shouldn't_ to cover up for others is nothing but nasty.

> And note that we already wipe from whole-disk device and it's necessary, so "care about PT only" is not true...

No. "wipe from whole-disk device" physically (or "logically" as in "logical block") will not touch any of the blocks covered by any of the old/new partitions before you run wipefs/mkfs. "care about PT only" was true except in cases like converting MBR to GPT.

It's not just about whether it is safe. It's more of the partitioning tool simply shouldn't play that role.

Also the per-partition prompt is definitely irritating to some extent, not to mention that it is unlikely necessary for the interactive fdisk _which would be used interactively_. So unless someone pointlessly run every mkfs/wipefs command with &>/dev/null when he is running them _by hand_, any hiccup could be noticed as well. (And I've never experienced or even heard of that myself TBH, considering I've done uncountable times of interactive installation with Arch ISO.)

**Comment by karelzak** [comment]
> No. "wipe from whole-disk device" physically (or "logically" as in "logical block") will not touch any of the blocks covered by any of the old/new partitions before you run wipefs/mkfs, except in cases like converting MBR to GPT, some of the filesystems could be ruined "unintentionally". So technically "care about PT only" was always true.

.. and except the case the disk has been used unpartitioned for FS or pretty often for RAIDs (imagine RAID1 signature on the end of the device). The same it's vice-versa, in mkfs-like programs we care (wipe) obsolete PTs.

> It's more of the partitioning tool simply shouldn't (have to) play that role.

Ah, ideal world... users use partitioning and mkfs tools pretty rarely, don't care or forget about wipefs and devices with horrible conflicting mess are not so unusual (although it's better last years).

IMHO the mistake is that you see FS and PT as something completely independent, but it's not true if you want to avoid conflicts and keep things usable for automatic detection. FS as well as PT is just signature somewhere on the device.

I agree that for example FS specific code in old GNU Parted was mistake, but this is not the same case.

Anyway, it seems like bikeshed-color topic now (from my point of view).
