### ISSUE TITLE
Device already mounted considered as mount failed

### ISSUE THREAD

**Issue by BNolet** [karelzak/util-linux#448]
Currently, if a device is already mounted, then exit code 32 is returned, signifying mount failure. 

However, if the device is already mounted, then there is no failure...well, it's already mounted. Perhaps return exit code 33 instead or even return 0 if we're looking at legacy issues.

Edit: looking in `libmount/src/context_mount.c` I see that the case for 'already mounted' is combined with 'device busy'. Hopefully it would be possible to make a distinction between the two without it being too costly.

**Comment by karelzak** [comment]
Frankly, I somehow lost in your report. Can you copy & past any example? I need some context...

Notes:
-  it's possible to mount the same filesystem more than once, all depends on FS kernel driver or VFS, EBUSY is returned if impossible
-  for "mount -a" we check for "already mounted" in userspace
-  for non-root users we check in userspace

**Comment by BNolet** [comment]
Is it possible to distinguish whether the device is busy or simply already mounted?

My issue is that "already mounted" ends up returning exit code 32 (mount failed) if it's already mounted, even if the device is not actually in the middle of a read/write. 
__________________
The script I've written attempts to mount a specific drive, backs up files using rsync, then unmounts the drive upon completion. 

This script fails when the drive is already mounted, thus copying info to an empty folder using up all of my boot drive's space, and causing a system failure of course. 

The only way I can fix this is to either run unmount then mount for the drive, or to manually check for the drive itself and whether it's mounted or not before running the script.

**Comment by karelzak** [comment]
I have doubts we can so easily distinguish between busy and already mounted from mount(2) syscall return code.

I think it will be better to improve your script to check if the mountpoint is mounted. This is my backup.sh:
```
findmnt $MOUNTPOINT &> /dev/null
if [ $? != 0 ]; then
        /bin/mount $MOUNTPOINT
        MOUNTED=1
fi
 
findmnt $MOUNTPOINT &> /dev/null
if [ $? != 0 ]; then
        echo "Backup ...failed to mount!" | /home/kzak/bin/xtext.sh
        exit 1
fi
```
... of course it's not 100% robust and there is race if you umount before you start backup or between findmnt and mount call, but it should be good enough for standard purpose.

**Comment by rudimeier** [comment]
On Tuesday 18 July 2017, Karel Zak wrote:
> I think it will be better to improve your script to check if the
> mountpoint is mounted.

Wouldn't it be better to check whether the *device* is mounted. 
Mountpounts can be mounted over and over again, while mounting a 
filesystem twice (writable) may be dangerous.

BTW I never really understood the "already mounted" error at all.

It's allowed to mount the same device to two different mountpoints.
It's also allowed to mount two different devices to the same mountpoint.

Both does not really make sense, but we only get an error if mounting 
the same device to the same directory.

**Comment by karelzak** [comment]
Yes, you can use devname for findmnt. 

The same FS on more places is pretty common (for example bind mount), different namespaces, etc. And different FS on the same mountpoint is also common, for example if you want new data for new instances of your daemon when old instances still running, system boot when you remount root fs, etc. These use-cases makes sense ;-)

And if I good remember you can also mount the same NFS on the same place more than once. All depends on FS driver.

**Comment by BNolet** [comment]
In that case, what code in which package/project would have to be modified? I take it this falls into the realm of the Linux Kernel if I'm not mistaken?

**Comment by sourcejedi** [comment]
I think it is wrong that `mount`ing from fstab does not run the check in advance, in the same way `mount -a` does.  Changing that might resolve the original use case.  I think it's wrong specifically _because_

> it's possible to mount the same filesystem more than once, all depends on FS kernel driver or VFS, EBUSY is returned if impossible

I think it's highly unexpected that `mount`ing _from fstab_ can create duplicate mounts.

```
# echo "/mnt /mnt none bind" >> /etc/fstab
# mount /mnt
# mount /mnt
# findmnt | grep mnt
findmnt|grep mnt
└─/mnt                                /dev/mapper/alan_dell_2016-fedora[/mnt] ext4            rw,relatime,seclabel,data=ordered
  └─/mnt                              /dev/mapper/alan_dell_2016-fedora[/mnt] ext4            rw,relatime,seclabel,data=ordered
    └─/mnt                            /dev/mapper/alan_dell_2016-fedora[/mnt] ext4            rw,relatime,seclabel,data=ordered
```

(the third mount is due to mount propagation).

This would not stop people from explicitly requesting `mount --bind /mnt /mnt`.  In that case `mount` does not refer to fstab, and it will let the user either see the kernel allowing it in whatever situations it allows it, or see the EBUSY result from the kernel.

**Comment by karelzak** [comment]
We don't plan to change the current behavior to introduce backwardly incompatible changes.

Note that detect "already mounted" filesystem is pretty tricky (including the current --all) and sometimes it's impossible due to changes in mount options, multi-root filesytems or network filesystems.

**Comment by sourcejedi** [comment]
I agree that code looks pretty tricky, and changing behaviour always risks breaking something that is not anticipated. (["This has been verified to work properly ... with the caveat that on centos6 and on slackware-14.1 that there wind up being two instances of the devpts filesystem mounted on /dev/pts, the lower copy does not end up getting used."](https://lwn.net/Articles/688809/)).

I can't help wondering why the code was written like that originally. To support multiple mounts on the same directory in fstab? To ensure fstab takes precedence, by overmounting in case a preceding boot script mounted a different FS?

Considering the limitations, perhaps this is one case I should be unambiguously happy that `systemd` changed from the traditional approach :).  (The equivalent of the `mount` init script, skips based on mount point only - it inherently does not check the device).

**Comment by karelzak** [comment]
Note that kernel behavior for classic filesystems like ext{2,3,4} is to return EBUSY error when you try to mount the same FS on the same mountpoint. So, there is no issue. 

Unfortunately, for pseudo filesystems (like tmpfs), network filesystems or bind mounts the situation is different and all mount(2) call creates a new FS instance. 

It would be possible to introduce a new command line option "--onlyonce" and maybe fstab option too to control this behavior. I'll add this to TODO file, we will see. Thanks.

**Comment by sourcejedi** [comment]
Sorry... you already solved the original request (and provide `mountpoint -q` too).

I don't have a practical use case that requires `--onlyonce`.  Even in bootstrapping /proc, and considering [future kernels where `proc` might be multi-instance by default](https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg1534362.html), I think testing with `mountpoint -q` (or `findmnt >& null`) would be just as good.

I imagine the new option might help in documenting `--all`.  But making it available as an fstab option as well, that sounds like the obvious logical conclusion, and yet I'm not sure if I like it. I can't decide if I would want any kind of `--onlyonce` option.

I lean towards writing this off.  It bothered me having read the C code, and after trying to make too close a comparison with `systemctl start $MOUNTPOINT`, but it doesn't seem to mean much in practice.

I think the only thing left that bothers me, is if there's a hole in the `mount -a` feature "due to changes in mount options, multi-root filesytems or network filesystems", and the hole wasn't mentioned when the feature was documented just now.

IMO the weirdness about when the _kernel_ check for double-mounts can do anything, is easier to gloss over.  My brain assumes that the kernel doesn't check for double-mounts.  If the check ever does help me, I'm liable to assume it was due to `/bin/mount`, and/or that it's a sanity check that probably doesn't work in all cases.  I don't think I would over-generalize and rely on it too much.

**Comment by sourcejedi** [comment]
I guess the problem with `onlyonce` as an fstab option, is that we're defining this as a mechanism to opt-in to backwards-incompatible behaviour.  Opting in on a per-invocation basis with `--onlyonce` sounds sane. But scoping it based on the fstab entry? It sounds like you have to guess which fstab entries it's safe and unsafe to set it on.

(On top of remembering that you wanted it... when it makes no practical difference for a lot of fstab entries).
