### ISSUE TITLE
Install only one module

### ISSUE THREAD

**Issue by flyingP0tat0** [karelzak/util-linux#494]
There is the option to only build one moule by using `make <module>`. But how can I install this one afterwards? `make <module> install` will continue with the compilation of the other modules.
Thank you.

**Comment by karelzak** [comment]
```
./configure --disable-all-programs --enable-hwclock
make install
```
Note that you have to also enable libs (e.g. --enable-libmount) if you want something what depends on the library (e.g. mount).

The problem is that we have no --enable/disable switches for all utils, but only for basic (or exotic) things. For example --enable-lsblk is not available. But if you have any use-case, than we can add a new --enable for you.

The ideal solution would be to have --enable-program <list>, but this is not implemented yet.
