### ISSUE TITLE
RFC: zramctl: autoload zram if not loaded

### ISSUE THREAD

**Issue by Nefelim4ag** [karelzak/util-linux#514]
subj,
if i understood correctly losetup do that, (AFAIK if i unload loop module, losetup still works and module magically loaded).

If that correctly (that losetup self load loop module), does that must be fixed for zramctl to have a same behaviour? 

Thanks.

P.S.
I give up to fix that myself, because i can't find where losetup loads loop module, looks like module do self-loading someway.

**Comment by karelzak** [comment]
No, losetup does not load anything, we don't want to such things in the tools like losetup.

The losetup just accesses /dev/loop-control. This is static note created by udevd on system boot (on Fedora see /usr/lib/udev/rules.d/50-udev-default.rules), this access triggers kernel event, the event is serviced by udevd and loop kernel module is loaded because according to modules.alias configuration
```
    alias devname:loop-control loop
```
is the loop-control mapped to "loop.ko". That's all.

Unfortunately, zram currently does not support common /dev node and alias to load the module. 

Note that zram uses /sys/class/zram-control directory for another purpose (add/remove /dev/zram<N> on the fly). It's not possible to use it for kernel module loading.

I really don't plan to  execute modprobe from zramctl. It would be better to improve kernel. For example I can imagine common node /dev/zram-load and use it to load the module. IMHO it's pretty simple kernel change.

Zram kernel maintainers are:     
 Minchan Kim <minchan@kernel.org>  
 Nitin Gupta <ngupta@vflare.org>
Please, CC: to me (kzak@redhat.com) if you plan to discuss this topic:)
