### ISSUE TITLE
sfdisk: ptbl reload timing issue

### ISSUE THREAD

**Issue by mauzi** [karelzak/util-linux#557]
Hi,
I'm using sfdisk 2.30.2 compiled from source on a x86-64 PC with kernel 4.9.x.

This one has 95%+ success rate:
  sfdisk /dev/sda < sda-dump

But this one always fails for me:
  sfdisk -q /dev/sda < sda-dump
or
  sfdisk /dev/sda < sda-dump > /dev/null

"Re-reading the partition table failed: Device or resource busy"

It looks like re-read happens too fast when there's no terminal output.

I have put a sleep() in sfdisk.c like this:
  if (!sf->notell) {
          sleep(1);
          fdisk_reread_partition_table(sf->cxt);
  }

and voila! It always succeeds!

Keep up the good work! libfdisk and (c|s)fdisk is great!

**Comment by mauzi** [comment]
FYI, on my PC:

- usleep(5000) has ~10% success ratio,
- usleep(10000) has ~50% success ratio,
- usleep(20000) is always success.

I think we should use 100000 - 500000 to be sure.

**Comment by karelzak** [comment]
Added 250000. Thanks for testing.

**Comment by markasoftware-tc** [comment]
Maybe should switch to `fdisk_reread_changes` instead of `fdisk_reread_partition_table` at https://github.com/util-linux/util-linux/blob/66063c6a9490c1b8fa515906ef03ba2979d1579a/disk-utils/sfdisk.c#L673 so that open files on other partitions can't cause a failure? not sure it would fix the original version of this issue but it is worth testing, may be able to get rid of the sleep.

**Comment by karelzak** [comment]
> Maybe should switch to `fdisk_reread_changes` instead of `fdisk_reread_partition_table` at

Good point; sfdisk was originally designed to "write new PT, ignore old", so from this point of view, a complete re-read makes sense. But we have `-N` and `--append` where the old table is just modified; in these cases, it would make sense to use `fdisk_reread_changes()`.
