### ISSUE TITLE
MS_REMOUNT in init_robind() causes other mount flags to be cleared

### ISSUE THREAD

**Issue by chenxiaolong** [karelzak/util-linux#637]
It seems that the current implementation of `init_robind()` for creating read-only bind mounts passes `MS_REMOUNT | MS_BIND | MS_RDONLY` to the mount syscall.

https://github.com/karelzak/util-linux/blob/475ecbad15943d6831fc508ce72016d581763b2b/libmount/src/context_mount.c#L134

This causes other flags from the source mount, like `MS_NOSUID`, to be cleared. For example:

    [mnt] mkdir source && sudo mount -t tmpfs -o nosuid tmpfs source
    [mnt] mkdir target && sudo mount --bind -o ro source target
    [mnt] mount | grep -E '(source|target)'
    tmpfs on /tmp/mnt/source type tmpfs (rw,nosuid,relatime,seclabel)
    tmpfs on /tmp/mnt/target type tmpfs (ro,relatime,seclabel)
    [mnt]

Notice that the bind mount no longer has `nosuid`, which is confusing because the behavior is different from a normal "rw" bind mount.

Would it be possible to update the function to include all existing mount flags from the source path? ie. `MS_REMOUNT | MS_BIND | MS_RDONLY | <existing flags>`.

**Comment by karelzak** [comment]
Good point. I restricted this functionality to MS_RDONLY years ago, because it was little bit controversial ("mount --bind" is two syscall in this case).

I think we can completely remove MS_RDONLY restriction from the code and make it usable for arbitrary VFS mount flags and without MS_RDONLY, for example
```
     # mount /dev/sdc1 /mnt/A
     # mount --bind -onosuid,noexec /mnt/A /mnt/B
    
     # findmnt /dev/sdc1 -oTARGET,SOURCE,FS-OPTIONS,VFS-OPTIONS
     TARGET SOURCE    FS-OPTIONS                 VFS-OPTIONS
     /mnt/A /dev/sdc1 rw,stripe=512,data=ordered rw,relatime
     /mnt/B /dev/sdc1 rw,stripe=512,data=ordered rw,nosuid,noexec,relatime
```

Note that "mount --bind <source> <target>" does not read existing mount flags from system. You have to specify all on mount command line. (Note that "mount -o remount <target>" has different semantic in this case.)
