### ISSUE TITLE
unshare --mount-proc=/xyz gets EINVAL

### ISSUE THREAD

**Issue by raylu** [karelzak/util-linux#648]
Passing an argument to `--mount-proc` generally doesn't work:

```
$ sudo unshare --mount --pid --fork --mount-proc=$PWD/rootfs/proc -- /bin/bash
unshare: mount /home/raylu/rootfs/proc failed: Invalid argument

$ sudo unshare --mount --pid --fork --mount-proc -- /bin/bash

$ unshare --version
unshare from util-linux 2.32

$ uname -a
Linux buster 4.16.0-2-amd64 #1 SMP Debian 4.16.12-1 (2018-05-27) x86_64 GNU/Linux
```

I believe this is because `unshare` always `mount()`s with the `MS_PRIVATE` flag: https://github.com/karelzak/util-linux/commit/6728ca101e#diff-5f9ec696d10433e2ceddf602db5b0261R151
which is only valid for changing the propagation type of an existing mountpoint, not for creating new mountpoints.

**Comment by mirfatif** [comment]
Due to the same reason:
`(mount("none", procmnt, NULL, MS_PRIVATE|MS_REC, NULL) != 0`
unshare expects the new mountpoint to be already a mountpoint so that it can be re-mounted PRIVATE.
Mounting the new mountpoint before executing unshare does the trick:
```
$ sudo mount -t proc proc $PWD/rootfs/proc
or
$ sudo mount -t tmpfs tmpfs $PWD/rootfs/proc
or
$ sudo mount -o bind $PWD/rootfs/proc $PWD/rootfs/proc
and then:
$ sudo unshare --mount --pid --fork --mount-proc=$PWD/rootfs/proc -- /bin/bash
```
But it's pointless. It's more simple to manually mount `procfs` after `unshare --pid`
