### ISSUE TITLE
fstrim(8) 2.33.2: fails on NTFS ro entry of fstab(5)

### ISSUE THREAD

**Issue by moviuro** [karelzak/util-linux#789]
Hi,

fstrim(8) fails on ro NTFS:
```sh
# grep ntfs /etc/fstab
UUID="F240DEA840DE7339" /mnt/F240DEA840DE7339 ntfs ro 0 0
# fstrim -Av
[.snip.]
fstrim: /mnt/F240DEA840DE7339: FITRIM ioctl failed: Bad file descriptor
```

Mounting the partition as `rw` makes fstrim(8) succeed, however I don't want nor need that partition to be `rw`.
```
/mnt/F240DEA840DE7339/: 184.1 GiB (197638004736 bytes) trimmed
```

I did try to change `ntfs` to `ntfs-3g`, but still the issue remains (`FITRIM ioctl failed: Bad file descriptor`).

I identified the issue on Archlinux, because I use the fstrim systemd.service(5) (which calls [`fstrim -Av`](https://github.com/karelzak/util-linux/blob/v2.33.2/sys-utils/fstrim.service.in)):
* ntfs-3g 2017.3.23-3
* linux 5.0.10.arch1-1
* util-linux 2.33.2-1

**Comment by kerolasa** [comment]
Some other reports about ntfs and fstrimL
* https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1797717
* https://forums.opensuse.org/showthread.php/532821-fstrim-FITRIM-ioctl-failed-Bad-file-descriptor
* https://bugs.archlinux.org/task/62288

I think comment at April 11 in archlinux bug from Dave Reisner is pretty reasonable. NTFS should fix what they return, and util-linux fstrim could alias EBADF. That said I pushed a commit to my git repo,  lets see what @karelzak thinks about that.

**Comment by karelzak** [comment]
Well, since commit fe7d63105d923d43c9f478acded0ac888463e456 (v2.34-rc1) does not call the ioctl for read-only devices (https://github.com/karelzak/util-linux/issues/738).

Not sure about  about read-only FS, add EBADF seems like a good idea. Maybe we can somehow print info about ignored errors if verbose > 1 (-vv). It seems strange to be always  silent :-)

**Comment by kerolasa** [comment]
I agree. Silencing errors feels like a slippery slope leading ultimately to miss genuine problems. But instead of --verbose I would rather see --quiet option to suppress warnings. That said the failure message could probably be made better. Perhaps something like

fstrim: /mnt/F240DEA840DE7339: ioctl failed to operate this device: Bad file descriptor

And some notes to manual page about well known problems, such as ntfs and bad file descriptor that seems to be pending driver authors fix.

**Comment by karelzak** [comment]
I like the idea with --quiet. We can make it more verbose by default and use --quiet in systemd service together with comment to explain why we use it.

@kerolasa do you want to a provide patch? It would be nice to have it fixed in -rc2 (yes, we have time:-)

**Comment by kerolasa** [comment]
Earlier commit is rebased and rewrote: https://github.com/karelzak/util-linux/pull/791 let me know if that's not good enough.

**Comment by karelzak** [comment]
Merged.
