### ISSUE TITLE
pkgconfig wrong dir

### ISSUE THREAD

**Issue by rdp** [karelzak/util-linux#793]
Building from source 5fcdf204b033297486e221a80a7f3c0a30734ceb

`make install` installs .pc files to /usr/lib/pkgconfig which apparently isn't recognized in CentOS 7.6  ( /usr/share/pkgconfig/ for instance is).  FWIW.

**Comment by kerolasa** [comment]
The pkg-config version 0.27 (since 2012-07-11) seems to have PKG_INSTALLDIR() macro that could be added to configure.ac and it would allow one to use --with-pkgconfigdir= when running ./configure. Could you give a try adding PKG_INSTALLDIR() after PKG_PROG_PKG_CONFIG in configure.ac and build again after using following option:

    ./configure --with-pkgconfigdir=/usr/share/pkgconfig

Ref: https://github.com/pkgconf/pkgconf/blob/master/pkg.m4#L217-L236

**Comment by karelzak** [comment]
@kerolasa It will not help, we have hardcoded path in our Makefile.am:

``` pkgconfigdir = $(usrlib_execdir)/pkgconfig```

the proper solution is to define all pkgconfigdir in configure.in.
