### ISSUE TITLE
fstrim --all should ignore bind mounts maybe

### ISSUE THREAD

**Issue by mgedmin** [karelzak/util-linux#857]
I've an Ubuntu 16.04 LTS server that runs `fstrim --all`` every week from cron.  And every week I receive an email saying

    fstrim: /var/spool/postfix/etc/sasldb2: not a directory

My /etc/fstab contains the following line

    /etc/sasldb2 /var/spool/postfix/etc/sasldb2 none bind 0 0

because I need postfix's smtpd to access /etc/sasldb2 (which is a regular file) inside the postfix chroot.

I think `fstrim --all` should ignore bind mounts if it doesn't know what to do with them.

Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1800167

**Comment by karelzak** [comment]
Good catch. You're right non-directory mountpoints should be silently ignored on --all/--fstab.

**Comment by matthijskooijman** [comment]
Shouldn't fstrim ignore *all* bindmounts? I've bindmounted subdirectories of a filesystem in other places, and now it ends up fstrimming some (not all, weirdly) of these, where only one of them reports discarded bytes and the rest (including the original mount) reports 0. Or maybe fstrim should group all mounts for the same filesystem and then only check (and report) on the "biggest" one of them (i.e. the original mount, but that might not be in the list of filesystems to trim).

**Comment by karelzak** [comment]
@matthijskooijman, fstrim de-duplicates the table of filesystems in two steps:
- first by target (mountpoint) in a backward direction
- and then by source (device) in the forward direction (first mounted device wins)
This applies to -A, -a, and -I.

It means if you have the original mount still mounted, it should be the winner; if it's not mounted, then the mounted subdirectory may be used.

**Comment by matthijskooijman** [comment]
*Edit: Note that my fstrim version is not recent (2.38), so maybe this was already resolved*

> It means if you have the original mount still mounted, it should be the winner; if it's not mounted, then the mounted subdirectory may be used.

That sounds like what I want, but does not seem to be happening when using `-listed-in` in the default Debian `fstrim.service`. E.g.:

```
root@tika:~# cat /root/fstab-minimized 
/dev/mapper/tika-data                  /data                       ext4    nofail,defaults,acl     0       2
/dev/mapper/tika-data--ssd             /data/ssd                   ext4    nofail,defaults,acl     0       2
/dev/mapper/tika-containers            /containers                 ext4    nofail,defaults,shared  0       2
/data/users                            /containers/ldap/data/users auto    nofail,defaults,bind         0   0
/data/ssd/ldap                         /containers/ldap/data/ldap  auto    nofail,defaults,bind         0   0
root@tika:~# fstrim --verbose --listed-in /root/fstab-minimized 
/containers/ldap/data/ldap: 0 B (0 bytes) trimmed on /data/ssd/ldap
fstrim: /containers/ldap/data/users: the discard operation is not supported
/containers: 459.8 MiB (482156544 bytes) trimmed on /dev/mapper/tika-containers
/data/ssd: 0 B (0 bytes) trimmed on /dev/mapper/tika-data--ssd
```

Above, running with a subset of my fstab (real fstab has dozens of mounts), it already shows the problem I am seeing. Weird things in the output above:
 -  I would expect `/data/ssd` to be used instead of `/data/ssd/ldap`, but both are shown (and the latter is shown first - here it shows 0B for /data/ssd/ldap, but that seems to be only because I ran the command a bunch of times, the weekly runs do show a byte number for the first bindmount of the `/data/ssd` filesystem).
 - This suggests to me that there is something weird in handling of bindmounts of a subdirectory.
 - However, `/data/` does not show up at all, even though it is listed.
 - `fstrim: /containers/ldap/data/users: the discard operation is not supported` is shown, but AFAICS it should be the same as `/containers/ldap/data/ldap` (bindmount of a subdirectory of a an ext4 mount with the same options on the same LVM VG and PV, no relevant differences in `tune2fs -l`). The only difference I can see is that the underlying mount has two different LVM LVs, of which one was originally allocated on an HDD and one on a SSD, but I cannot see any relevant LVM LV options/flags that affect this (there is an `lvchange --discards`, but that seems to be applied only to thin volumes, it is also not displayed by `lvdisplay`).

**Comment by matthijskooijman** [comment]
Wait, I see I still have an older fstrim version (2.38), so maybe this behavior was changed since then? I'll upgrade the system first (might take a while) and then rerun the above test.

**Comment by karelzak** [comment]
@matthijskooijman, thanks for the fstab sample — the issue is clear now.

The problem is that fstrim de-duplicates by source (device) path, but fstab entries like

    /data/ssd/ldap    /containers/ldap/data/ldap    auto    bind

use a directory path as the source, not a device name. So `"/data/ssd/ldap"` never matches `"/dev/mapper/tika-data--ssd"` in the de-duplication step, even though they refer to the same filesystem. With `--all` (mountinfo), this works because the kernel always provides the real block device.

The fix is to use `statmount(STATMOUNT_SB_SOURCE)` to resolve the actual device from the kernel for each mountpoint before de-duplication. This also handles multi-device filesystems (btrfs) correctly, unlike a plain `stat()` approach.

This is still an issue in the current code, not specific to 2.38.
