### ISSUE TITLE
The blkdiscard should really warn user what's going to happen to the data

### ISSUE THREAD

**Issue by xhorak** [karelzak/util-linux#892]
That the data will be completely lost and unrecoverable.

**Comment by karelzak** [comment]
We have a fat big warning in the man page:
```
 WARNING: All data in the discarded region on the device will be lost!
```
If you use as root random tools for your block devices without man page reading than it's fine and expected that you lost data, what else...

**Comment by karelzak** [comment]
Note that I do not see any elegant way how to protect users against their mistakes. I think maintain any system requires a little bit responsibility. Yes, we can implement some countdown before the action, the problem is that it may be used in scripts, etc. .. and introduce terminal (interactive) specific behaviour will increase complexity in semantic, etc.
