### ISSUE TITLE
RFE: libfdisk: ability to create partition tables covering only a part of the block device

### ISSUE THREAD

**Issue by poettering** [karelzak/util-linux#907]
I'd like to be able to generate "minimal partition tables" with libfdisk, so that when I have a block device that is 1G large, but I only place two 100M partitions on it, the area covered by the GPT partition table is only the first 200M and the remaining 824M are not covered by the GPT table, as  if they wouldn't exist. The GPT footer sector would hence be somewhere in the middle of the physical device, and not at the end.

I think that for GPT itself I could implement that with fdisk_set_last_lba() knowing that how long the gpt footer is, however i'd prefer to do that in a GPT agnostic way, i.e. fdisk_set_nsectors() or so, from which fdisk then derives what it needs to know...

(Alternatively — or additionally —, a simple boolean would be nice: fdisk_set_minimize_disk_label(), which when set would mean libfdisk would automatically determine the smallest it can make the whole table (i.e. by looking for the end of the last partition) and then sizing things automatically, so that when fdisk_get_nsectors() is called then it returns a much smaller value than the block device actually is)

I hope the above makes some sense?

**Comment by karelzak** [comment]
GPT itself implements "partitionable area" -- it means an area where is possible to create partitions, but in this case, primary and backup headers are still at begin and the end of the device. I guess you don't want it in this way.

We can implement something live we have in libblkid where the device is possible to restrict by the begin and size. Something like:
```
 fdisk_assign_device(cxt, "/dev/sda", 0);
 fdisk_set_device_dimension(cxt, 0, 200 * 1024 * 1024 / sector_size);

or

 fdisk_assign_device_with_dimension(cxt, "/dev/sda", 0, 0, 200 * 1024 * 1024 / sector_size);
```
to define  /dev/sda as 200MiB from sector 0.

Note that you will be not 100% compatible with the UEFI standard as it assumes that GPT covers the whole device, and the backup header is at the end. Still, your use-case is nothing unusual, and I have already seen it for some install images, and the Linux kernel was modified to support it years ago (commit 87fc0ad2ad8a15de653f4cef7760fa35e689077f).

**Comment by poettering** [comment]
So, begin + size a a fdisk_set_device_dimension() would be excellent (actually, the begin doesn't matter to me, only the size), so I'd happily take that.

Any chance we can then also get fdisk_minimize_device_dimension()? which would look at the partitions defined, determine the smallest covering area, add space for correct footer and header and then determine size from that passing it to disk_set_device_dimension()? that would be more than ideal for my usecase...

Yes, I am aware that images done this way are not how GPT is originally intended to be used, but it's already how dd'able images will look like, right? I want "maximum dd'ability" if you get my gist ;-)

**Comment by DidierSpaier** [comment]
I would be reluctant to use a feature that does not comply with the UEFI specification and don't get the "it's already how dd'able images will look like" argument. Being not an expert I will request Thomas Schmitt's opinion on this matter.

**Comment by scdbackup** [comment]
Hi,

the GPT specs in UEFI specs say that the backup header block must sit
in the last block of the device.
UEFI 2.4, 5.3.1 "GPT overview":
  Two GPT Header structures are stored on the device: the primary and the
  backup. The primary GPT Header must be located in LBA 1 (i.e., the second
  logical block), and the backup GPT Header must be located in the last LBA
  of the device.

Putting it anywhere else makes few sense, if the result shall be subject
to GPT oriented tools. EFI firmware seems to ignore this flaw, though.
grub-mkrescue ISOs boot from USB stick despite misplaced backup header.


poettering wrote:
> I want "maximum dd'ability" if you get my gist ;-)

Because of this backup header, GPT is not well suited for image files which
later shall be copied onto a real device. I propose to xorriso users not to
use GPT partitioning but rather old-fashioned MBR. It is open ended and can
mark an EFI partition as can GPT.
UEFI 2.4, 5.2.2 "OS Types" says:
  "0xEF (i.e., UEFI System Partition) defines a UEFI system partition."

Actually most of the usual isohybrid ISOs have GPT only as invalid ornament
and boot via MBR partitions of type 0xEF. If there is 0xEF, the MBR is not
"protective" and thus indicates no valid GPT.
I analyzed this non-optimal layout of Debian ISOs in
  https://lists.debian.org/debian-cd/2019/07/msg00007.html
  "Proposal to change partition table layouts for EFI bootable ISOs"
where i propose to drop GPT entirely and to avoid nested MBR partitions.

grub-mkrescue (used e.g. by Guix ISO production) produces valid GPT with the
drawback that no ISO 9660 partition exists.
(So the ISO filesystem will not be detectable by blkid after
   https://github.com/karelzak/util-linux/commit/7ef86a08914427d6486734614d7d3bbed1f108fe
 which disabled the base device as reportable carrier of ISO 9660 and causes
   https://bugzilla.redhat.com/show_bug.cgi?id=1783066
)

As said, EFI likes these ISOs. But expect complaints about damaged table
when GPT editors shall operate on the storage device which was filled by
such an ISO.

Have a nice day :)

Thomas

**Comment by karelzak** [comment]
@scdbackup the situation when it's incompatible with UEFI standard is a semi-finished product. After GPT reduction (move backup header after the last partition) you can reduce all the image. So the result will be an install image that is compatible with the standard. 

Let's imagine you create 1GiB image with GPT, install your OS and then you want to remove all free space to keep it small. It's simple to resize filesystems and then resize partitions. The problem is that we have no tool to resize all GPT (move backup header after the last partition and update necessary fields in the GPT headers).

**Comment by poettering** [comment]
Yeah, it might be cool btw if libfdisk would optionally even ftruncate() the resulting image file if we are operating on an image file instead of a block device.

**Comment by karelzak** [comment]
@poettering maybe set device dimension (size, etc.) is unnecessary (or overkill).

You have suggested fdisk_set_minimize_disk_label() boolean as alternative, it seems better direction. I would suggest fdisk_minimize_disklabel() operation, which will be possible to use in an arbitrary situation when the disklabel already exists. After this operation, in-memory GPT will be reduced
to avoid the gap between the last partition and the backup GPT header.

(Note that libfdisk keeps GPT header in memory and write operation writes it to the device only; it does not generate GPT on write, it's created when you create new header or assign a device).
```
  cxt = fdisk_new_context()
  fdisk_assign_device(cxt, "/dev/sda", 0);
  fdisk_minimize_label(cxt);
  fdisk_write_disklabel(cxt);
  fdisk_deassign_device(cxt);
  fdisk_unref_context(cxt);
```
it would be also possible to support it by sfdisk (e.g. sfdisk --minimize foo.img).

**Comment by scdbackup** [comment]
Hi,

> The problem is that we have no tool to resize all GPT (move backup header
> after the last partition and update necessary fields in the GPT headers).

I understand that this is GPT compliant if the image file gets truncated
to end directly after the backup header block. One could use that file as
virtual device.

But when the image gets onto a real storage device which is larger than 
the file, then it is not compliant any more.

A tool seems missing to do the contrary of the current plan: Expand GPT to 
the full storage device size.
It would be very helpful for users of grub-mkrescue ISOs like the Guix
installation ISOs. (dd onto stick, run GPT expander, make data partition.)

On this occasion, let me express my great appreciation for lsblk and blkid.
Thanks to all who are providing them.

Have a nice day :)

Thomas

**Comment by karelzak** [comment]
@scdbackup  libfdisk is already able to detect situation when the primary and backup header are valid, but backup is not at the end of the device, In this case, the backup header is moved to the end.
```
        /* The headers make be correct, but Backup do not have to be on the end
         * of the device (due to device resize, etc.). Let's fix this issue. */
        if (le64_to_cpu(gpt->pheader->alternative_lba) > cxt->total_sectors ||
            le64_to_cpu(gpt->pheader->alternative_lba) < cxt->total_sectors - 1ULL) {
                fdisk_warnx(cxt, _("The backup GPT table is not on the end of the device. "
                                   "This problem will be corrected by write.")); 
                 
                gpt_fix_alternative_lba(cxt, gpt);
                gpt_recompute_crc(gpt->bheader, gpt->ents);
                gpt_recompute_crc(gpt->pheader, gpt->ents);
                fdisk_label_set_changed(cxt->label, 1);
        }        
```
The problem is that you need to do somethign with the GPT to trigger this code.

Maybe we need "sfdisk --fix" or so :-)

**Comment by scdbackup** [comment]
Hi,

> Maybe we need "sfdisk --fix" or so :-)

I just wanted to ask by what shell command i could make use of this. :))

Please provide such a feature.
An option name like "--expand-gpt" seems more on point, though, unless you
plan to bundle more rectification use cases.

(I will now have to explore how i can trigger the fix by sfdisk activity.
Already that would be helpful for the most cases. The GPT mis-size becomes
annoying mainly when one wants to change the partitioning.)

Have a nice day :)

Thomas

**Comment by poettering** [comment]
@karelzak yeah, habing just such a minimization API would suffice to me. But I'd need an API to query the resulting overall size. i.e. so that I know where to truncate/stop dd'ing...

**Comment by karelzak** [comment]
Implemented;
* use fdisk_gpt_enable_minimize() to move behind last partition
* and use fdisk_gpt_disable_relocation() to avoid automatic relocation

Command-line example, create standard GPT:
```
# modprobe scsi_debug dev_size_mb=100
# echo -e ',+10M,L' | ./sfdisk --label gpt /dev/sdc

# ./fdisk --list-details /dev/sdc | grep Alt
Alternative LBA: 204799
```
and now move backup header:
```
# ./sfdisk --relocate gpt-bak-mini /dev/sdc
# ./fdisk --list-details /dev/sdc | grep Alt
The backup GPT table is not on the end of the device.
Alternative LBA: 22561
```
and move it back:
```
# ./sfdisk --relocate gpt-bak-std /dev/sdc
The backup GPT table is not on the end of the device. This problem will be corrected by write.
...
# ./fdisk --list-details /dev/sdc | grep Alt
Alternative LBA: 204799
```

Note that --relocate and --list-details are new sfdisk and fdisk command-line options.

So, now you have tools to do "bad" things ;-) I'll add some regression test for this later.
