### ISSUE TITLE
ext4 fs label: trailing space is stripped in blkid probe

### ISSUE THREAD

**Issue by yanniszark** [karelzak/util-linux#965]
**What happened:**

blkid reports ext4 FS LABEL without trailing spaces.

**What did you expect to happen?**

blkid should report ext4 FS LABEL with trailing spaces.

**How to reproduce:**

1. Get a spare block device (e.g., a loop device). We call it $DEV.
2. `mkfs.ext4 $DEV -L 'trailing space '`
3. `blkid -p $DEV`

Confirm correct value with `e2label`:
`e2label $DEV`

**Environment:**

- Version: blkid from util-linux 2.34  (libblkid 2.34.0, 14-Jun-2019)
- OS: Debian GNU/Linux bullseye/sid

/cc @alextsits

**Comment by karelzak** [comment]
This is an expected feature, see
https://github.com/karelzak/util-linux/blob/master/libblkid/src/superblocks/superblocks.c#L665

We use it because in some cases filesystems use blank space (rather than \0) to fill the rest of the area where the label is stored in filesystem superblock. The libblkid also internally provides LABEL_RAW which is without any modification -- but it's nowhere exported to the command line.

Another reason is that people rarely use LABEL="quotes" and in some tools it's (or was for years) unsupported.

I don't think we can change it after 12 years as it will have to impart to mount, fsck, etc.

Closing, sorry.

**Comment by yanniszark** [comment]
@karelzak thanks for explaining why it works that way :smile:
