### ISSUE TITLE
rev utility limited to files of size 2GB

### ISSUE THREAD

**Issue by jfostier** [karelzak/util-linux#972]
The rev utility cannot reverse files larger than roughly 2GBytes. Likely the issue is the use of a signed 32 bit integer somewhere.

**Comment by karelzak** [comment]
It depends. Don't forget it's lines and chars oriented tool.

If you have a huge file with relatively small lines than it works as expected (tested on 5GiB file). The problem is if you have 2GiB file without a line break. It allocates a buffer to read the whole line to reverse it. It uses size_t, standard malloc() and fgets().

Maybe it would be possible to search for \n in the file and use lseek and small buffers, but not sure if it makes sense for a small tool that is usually used in pipes.

**Comment by jfostier** [comment]
I was reversing the human genome (about 3G characters) to build a bidirectional FM index. I used the split tool to work around the issue. But maybe at least a warning should be nice.

**Comment by karelzak** [comment]
Nice to see that the basic Linux tools for this kind of task. I have added a note about the current implementation limitations to the man page and new item to our TODO file.
