### ISSUE TITLE
hwclock does not set kernel timezone with musl

### ISSUE THREAD

**Issue by neheb** [karelzak/util-linux#995]
https://git.musl-libc.org/cgit/musl/tree/src/linux/settimeofday.c#n7

Notice how the tz argument is completely unused. Probably because it's deprecated functionality.

The OpenWrt solution is to call the syscall directly.

**Comment by karelzak** [comment]
You probably want to report it to musl developers ;-)

I think better than silently ignore the tz argument is the glibc-way (since glinc v2.31) where it returns error when both arguments used. See our commit cd781c405be82540484da3bfe3d3f17a39b8eb5c.

Yes, it seems we need to define our own calls to avoid libc developers creativity...
Thanks for your report.

**Comment by neheb** [comment]
I don’t think musl is doing anything wrong. The tz variable has been deprecated since POSIX 2008. It’s unfortunate but so is the whole situation based on what I’ve regarding setting the kernel time zone and not having a 64-bit syscall.

**Comment by karelzak** [comment]
Fixed by commit 9c6139a72017cecb9145e46102152cb4f456ada6.
